# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 16:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stakeholder', models.CharField(max_length=70)),
                ('project_name', models.CharField(max_length=100)),
                ('project_category', models.CharField(choices=[('1', 'Training & Development'), ('2', 'Customer Experience'), ('3', 'Process Improvement'), ('4', 'IT'), ('5', 'Management & Controls')], max_length=70)),
                ('project_details', models.TextField()),
                ('project_phase', models.CharField(choices=[('0', 'Backlog'), ('1', 'Ramp-Up'), ('2', 'Go_No-Go Decision'), ('3', 'Development_Implementation'), ('4', 'Stabilization'), ('5', 'Project Closing')], max_length=2)),
                ('status', models.CharField(choices=[('1', 'Not Started'), ('2', 'In Progress'), ('3', 'Completed'), ('4', 'On Hold')], max_length=50)),
                ('cost_estimate', models.IntegerField()),
                ('actual_cost', models.IntegerField()),
                ('create_date', models.DateTimeField(default=datetime.datetime(2017, 8, 31, 16, 49, 30, 932779, tzinfo=utc))),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='resource_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Resource'),
        ),
    ]
