# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='create_date',
        ),
    ]
