# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_project_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='resource_id',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
